version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "57000:8080"
    command:
      - "./bin/run_uvicorn_server.sh"
    volumes:
      - .:/workspace
