#default parameters




default:
  rotations: {}
  parameters:
    exposure: -5
    resWidth: 640
    resHeight: 480
    framerate: 25
    codec: DIVX

#saved parameters    





saved:
  rotations:
    0: 90
    1: 270
    2: 90
    4: 90
  parameters:
    exposure: -6
    resWidth: 640
    resHeight: 480
    framerate: 30
    codec: H264
